### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by xeruf** [MattDahEpic/MonstercatDownloader#1]
Does it work for you? for me the progress-panel opens but is never updated, only question marks

**Comment by MattDahEpic** [comment]
I no longer have a monstercat gold membership and am unable to test this program. This program was created prior to monstercat's API move and may be affected by it.

**Comment by xeruf** [comment]
well, actually, I want to create something like this myself and wanted some inspiration. But for some reason I can't get the received json parsed.
And btw it should not be affected by the move because everything your application uses from connect is still hosted there

**Comment by EtzBetz** [comment]
Works fine for me on Windows 10. Didn't run on macOS for some reason, maybe I'll try to figure out why. (File Selection doesn't show)

**Comment by madziaar** [comment]
it would be nice if it got auto-reconnect feature (if it does it doesn't work for me) because my internet resets from time to time...

**Comment by xeruf** [comment]
Alright, for people randomly stumbling into this I have created my own pretty sophisticated tool: https://github.com/Xerus2000/monsterutilities

**Comment by MattDahEpic** [comment]
Awesome! I'll add a link to the readme. Great work
